[metadata]
name = wheely-pythia
author = Seth Just
author_email = sjust@seer.bio
description = Reader for Pythia results, compatible with wheely-mammoth
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/seerbio/wheely-pythia
project_urls =
    Bug Tracker = https://github.com/seerbio/wheely-pythia/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Bio-Informatics

[options]
packages = find:
python_requires = >=3.6
install_requires =
    pyspark>=3.3.1,<4.0.0
    wheely-mammoth>=0.10.0,<1.0.0

[options.extras_require]
hdf =
    h5py>=3.7.0,<4.0.0
docs =
    numpydoc>=1.0.0
    sphinx-argparse>=0.2.5
    sphinx-rtd-theme>=0.5.0
    nbsphinx>=0.7.1
    ipykernel>=5.3.0
    recommonmark>=0.5.0
dev =
    pre-commit>=2.7.1
    black>=20.8b1
    pytest

[options.entry_points]
# Legacy plugin location -- only used w/ Scry < 0.7.0
scry.search.existing.plugins =
    pythia = wheely_pythia.parsers:read_pythia_features

wheely.mammoth.parsers.plugins =
    pythia = wheely_pythia.parsers:read_pythia_features
wheely.mammoth.spectra.plugins =
    pythia = wheely_pythia.parsers:read_pythia_spectra
